name: "Code Cleanup"

on: 
  pull_request:
    branches:
      - main
  
jobs:
  laravel-pint:

    name: "Laravel Pint"
    runs-on: ubuntu-latest
    steps:
      # Checkout our codebase
      - name: Checkout code
        uses: actions/checkout@v4
      # Set up PHP
      - uses: shivammathur/setup-php@2.31.1
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr
          tools: composer:v2
      # Global installation of Pint
      - name: "Install Pint"
        run: composer global require laravel/pint
      # Install composer dependencies
      - name: "Install Project Dependencies"
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      # Execute Laravel Pint
      - name: "Execute Laravel Pint"
        run: "pint --test"
      # Commit back to repo
    
    
